import React from 'react';

const CookiesPolicy: React.FC = () => {
  return (
    <div className="container mx-auto px-4 py-8 text-sm md:text-base">
      <h1 className="text-3xl font-bold mb-4">Cookies Policy — Diana Global</h1>
      <p className="mb-4">Last updated: 10/14/2025</p>

      <p className="mb-4">
        This Cookies Policy explains how Diana Global (“we”, “us”, or “our”) uses cookies and similar
        technologies on our websites, the Diana Wallet, and the decentralized exchange (DEX)
        (collectively, the “Services”). By continuing to browse or use the Services, you consent to the
        use of cookies as described here, subject to your preferences.
      </p>

      <h2 className="text-2xl font-bold mb-2">1. What Are Cookies?</h2>
      <p className="mb-4">
        Cookies are small text files stored on your device by a website. They help the site remember
        your actions and preferences (such as login, language, and region) over a period of time.
        Similar technologies (e.g., pixels, local storage) may also be used for related purposes.
      </p>

      <h2 className="text-2xl font-bold mb-2">2. Types of Cookies We Use</h2>
      <ul className="list-disc list-inside mb-4">
        <li className="mb-2">
          <strong>Strictly Necessary:</strong> Required for core functionality (e.g., security, session,
          routing). These cannot be switched off in our systems.
        </li>
        <li className="mb-2">
          <strong>Analytics (GA4):</strong> Help us understand how visitors interact with the Services
          (page views, session metrics, events) so we can improve performance and UX. Enabled only with
          your consent.
        </li>
        <li className="mb-2">
          <strong>Marketing:</strong> Used to measure campaign effectiveness or personalize content.
          Disabled by default and only enabled with your explicit consent (if/when used).
        </li>
      </ul>

      <h2 className="text-2xl font-bold mb-2">3. Cookies We Set</h2>
      <ul className="list-disc list-inside mb-4">
        <li className="mb-2">
          <strong>Consent cookie:</strong> Remembers your choices regarding analytics/marketing cookies
          (e.g., <code>cookie_consent_v1</code>).
        </li>
        <li className="mb-2">
          <strong>Session/necessary cookies:</strong> Support authentication flows, routing, and security.
        </li>
        <li className="mb-2">
          <strong>Google Analytics 4 (GA4):</strong> Set only if analytics is accepted. Typical cookies include
          <code> _ga</code> and related identifiers generated by Google Tag (<em>the exact names may vary
          by configuration</em>).
        </li>
      </ul>

      <h2 className="text-2xl font-bold mb-2">4. Google Analytics 4 (GA4)</h2>
      <p className="mb-4">
        When you accept analytics cookies, we load Google Analytics 4 to collect aggregated usage
        statistics (e.g., sessions, events, referrers). We configured GA4 to respect your consent and to
        avoid collecting personally identifying information. You can withdraw consent at any time via
        the cookie banner or preferences.
      </p>

      <h2 className="text-2xl font-bold mb-2">5. Managing Your Preferences</h2>
      <p className="mb-4">
        You can accept or reject analytics/marketing cookies via our banner. If you previously accepted
        and want to change your choices, clear your browser cookies or revisit the banner (e.g., by
        using the “Manage Cookies” link in the footer, if available). Note that strictly necessary
        cookies cannot be disabled because they are essential for the Services to function.
      </p>

      <h2 className="text-2xl font-bold mb-2">6. Data Retention</h2>
      <p className="mb-4">
        Cookies have varying lifespans. We aim to retain analytics data only as long as necessary for
        the purposes described. GA4 retention can be configured within Google Analytics admin settings.
      </p>

      <h2 className="text-2xl font-bold mb-2">7. Changes to This Policy</h2>
      <p className="mb-4">
        We may update this Cookies Policy from time to time. Any material changes will be posted on this
        page. Continued use of the Services after changes take effect constitutes your acceptance.
      </p>

      <h2 className="text-2xl font-bold mb-2">8. Contact</h2>
      <address className="not-italic mb-4">
        <strong>Diana Global</strong><br />
        Email: andescoresoftware@gmail.com
      </address>

      <h2 className="text-2xl font-bold mb-2">9. Governing Law & Venue (Brazil)</h2>
      <p className="mb-4">
        This Cookies Policy shall be governed by the laws of the Federative Republic of Brazil. Any
        dispute shall be resolved exclusively by the courts of the City of São Paulo, State of São
        Paulo, Brazil, without prejudice to mandatory consumer protection rules that may apply.
      </p>
    </div>
  );
};

export default CookiesPolicy;
